#!/usr/bin/env python3
"""Bundle the Material Symbols icon names the bundled font can render.

The add-note screen offers an icon search: the user types part of a name and the
screen shows every matching glyph. The names are the font's ligature
substitutions (``rlig``/``rclt``), so the full set is extracted from the newest
``app/src/main/assets/material-symbols-*.ttf`` and written as a generated Kotlin
source file in ``:ui``, where the add-note screen reads it.

The list is regenerated by hand whenever the bundled font is updated, like the
other bundled assets:

    python3 bundle_icons.py

The generated file is committed; this script never runs as part of the build.
"""

import json
import sys
from pathlib import Path

from fontTools.ttLib import TTFont

REPO_ROOT = Path(__file__).resolve().parent
ASSETS_DIR = REPO_ROOT / "app" / "src" / "main" / "assets"
OUTPUT_FILE = (
    REPO_ROOT
    / "ui"
    / "src"
    / "commonMain"
    / "kotlin"
    / "org"
    / "btcmap"
    / "ui"
    / "MaterialSymbolNames.kt"
)

# Keep each generated function small so its bytecode stays well under the JVM
# method-size limit; 4275 names in a single function would not compile.
CHUNK_SIZE = 1000

# The characters icon names are actually typed with. A ligature's components are
# glyph names, so a glyph that has no ASCII character here is skipped.
NAME_CHARS = "abcdefghijklmnopqrstuvwxyz0123456789_"


def newest_font() -> Path:
    """The newest bundled Material Symbols font, by filename."""
    fonts = sorted(ASSETS_DIR.glob("material-symbols-*.ttf"))
    if not fonts:
        raise SystemExit(f"no Material Symbols font found in {ASSETS_DIR}")
    return fonts[-1]


def _glyph_chars(font: TTFont) -> dict[str, str]:
    """Map the font's glyph names to the characters they encode.

    A ligature's components are glyph names (``digit_two``, ``underscore``), not
    characters. Joining them verbatim yields ``add_digit_two`` instead of
    ``add_2``, a name the font has no ligature for, so the UI renders it as
    literal text. The reverse cmap restores the characters users actually type.
    """
    chars: dict[str, str] = {}
    for codepoint, glyph_name in (font.getBestCmap() or {}).items():
        character = chr(codepoint)
        if character in NAME_CHARS:
            chars.setdefault(glyph_name, character)
    return chars


def _walk_lookup(lookup, names: set[str], chars: dict[str, str]) -> None:
    subtable = lookup.SubTable
    subtables = subtable if isinstance(subtable, list) else [subtable]
    for sub in subtables:
        _walk_subtable(lookup.LookupType, sub, names, chars)


def _walk_subtable(
    lookup_type: int,
    subtable,
    names: set[str],
    chars: dict[str, str],
) -> None:
    # An extension lookup wraps another lookup that carries the real type.
    if lookup_type == 7:
        _walk_subtable(
            subtable.ExtensionLookupType, subtable.ExtSubTable, names, chars
        )
        return
    if not hasattr(subtable, "ligatures"):
        return
    for first, ligatures in subtable.ligatures.items():
        for ligature in ligatures:
            parts = [first, *ligature.Component]
            names.add("".join(chars.get(part, part) for part in parts))


def extract_names(font_path: Path) -> list[str]:
    """Every distinct icon name the font's ligature substitutions define."""
    font = TTFont(font_path)
    gsub = font["GSUB"].table
    chars = _glyph_chars(font)
    names: set[str] = set()
    for lookup in gsub.LookupList.Lookup:
        _walk_lookup(lookup, names, chars)
    return sorted(names)


def render_kotlin(names: list[str], font_name: str) -> str:
    chunks = [
        names[index : index + CHUNK_SIZE]
        for index in range(0, len(names), CHUNK_SIZE)
    ]

    lines = [
        "// Generated by ./devtools bundle icons from "
        f"app/src/main/assets/{font_name}. Do not edit by hand.",
        "",
        "package org.btcmap.ui",
        "",
        "/**",
        " * Every Material Symbols ligature name the bundled icon font can render,",
        " * used by the add-note screen's icon search.",
        " *",
        f" * Generated from `{font_name}`; regenerate with",
        " * `./devtools bundle icons` after the bundled font is updated.",
        " */",
        "internal val MATERIAL_SYMBOL_NAMES: List<String> = buildList {",
    ]
    for index in range(len(chunks)):
        lines.append(f"    addAll(materialSymbolNamesChunk{index}())")
    lines.append("}")
    lines.append("")
    for index, chunk in enumerate(chunks):
        lines.append(
            f"private fun materialSymbolNamesChunk{index}(): List<String> = listOf("
        )
        lines.extend(f"    {json.dumps(name)}," for name in chunk)
        lines.append(")")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    font_path = newest_font()
    names = extract_names(font_path)
    if not names:
        raise SystemExit(f"no icon names extracted from {font_path}")
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(render_kotlin(names, font_path.name), encoding="utf-8")
    print(f"Wrote {len(names)} icon names to {OUTPUT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
