package org.btcmap.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.dp

/** The already-resolved strings the invoice block renders. */
data class InvoicePaymentLabels(
    val qrDescription: String,
    val pay: String,
    val copy: String,
    val startOver: String,
)

/**
 * The Lightning invoice block shared by the boost and comment payment screens:
 * the QR code, the pay and copy actions and the start-over escape hatch.
 *
 * The QR is generated by the Android host; a null [qr] hides the whole block.
 */
@Composable
fun InvoicePayment(
    qr: ImageBitmap?,
    labels: InvoicePaymentLabels,
    onPay: () -> Unit,
    onCopy: () -> Unit,
    onStartOver: () -> Unit,
    modifier: Modifier = Modifier,
) {
    if (qr == null) return

    Column(
        modifier = modifier.fillMaxWidth(),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Image(
            bitmap = qr,
            contentDescription = labels.qrDescription,
            contentScale = ContentScale.Fit,
            modifier = Modifier
                .fillMaxWidth()
                .height(230.dp)
                .padding(horizontal = 40.dp),
        )

        Row(
            modifier = Modifier.padding(horizontal = 40.dp, vertical = 16.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Button(
                onClick = onPay,
                modifier = Modifier.padding(end = 8.dp),
            ) {
                Text(labels.pay)
            }
            TextButton(
                onClick = onCopy,
                modifier = Modifier.padding(start = 8.dp),
            ) {
                Text(labels.copy)
            }
        }

        TextButton(
            onClick = onStartOver,
            modifier = Modifier.padding(bottom = 16.dp),
        ) {
            Text(labels.startOver)
        }
    }
}
